### ISSUE TITLE
Cannot deploy: symfony_cache_path undefined

### ISSUE THREAD

**Issue by novacp** [capistrano/symfony#64] opened 2016-07-01 09:55 UTC
I was trying to use capistrano symfony, therefore I followed your docs here on github but when I try to deploy, I receive the following error:

"NameError: undefined local variable or method 'symfony_cache_path' for #SSHKIT:Backend::Printer:0x2f8b360.

This error occurs within symfony.rake, when trying to run the task "symfony:create_cache_dir".
I inspected the file "symfony.rake" and could not find from where the variable "symfony_cache_path" should be filled.

Did I miss something? I think, that I did not understand well on how to use a git repository within capistrano symfony. 

I am developing on a dev machine lets say with ip .67, and the code is being versionised on another virtual machine with ip .68 by using Git and Bitbucket. In deploy.rb, I tried to connect to the git repo. In development, I am using an ssh key to push changes to the bitbucket - so I thought when using the same user from the dev machine in the deploy.rb file, I should also be able to connec to git repo:

set :repo_url, 'ssh://git@xxx.xxx.xx.68:7999/nav/myrepo.git'
set :ssh_user, 'jenkins'
server 'http://xxx.xxx.xx.68', user: fetch(:ssh_user), roles: %w{web app db}

When running this, I get the error described above..

**Comment by Nico-h** [comment] 2016-08-02 16:11
Hi there,

I have got the same error... :(

**Comment by wasbaiti** [comment] 2016-09-16 07:41
Hello
I encounter the same bug
my deployment is successful without capistrano/symfony
as soon as I add capistrano/symfony, it no longer works
I use gitlab and symfony3 and everything is on ubuntu servers

**Comment by nescim** [comment] 2016-12-19 09:37
It looks like this is a duplicate of #63.
Also, did anyone find a workaround?

**Comment by Nyholm** [comment] 2018-09-06 21:53
Closing this due inactivity. Feel free to ping me if this is still an issue.

**Closed by Nyholm** 2018-09-06 21:53 UTC
