### ISSUE TITLE
Symfony 4 directory structure

### ISSUE THREAD

**Issue by TNAJanssen** [capistrano/symfony#83] opened 2017-10-09 09:06 UTC

**Comment by Soullivaneuh** [comment] 2017-12-19 20:48
Any help needed to maintain this repository? 4.0 is now stable, it would be great to have this update soon.

**Comment by will-in-wi** [comment] 2017-12-20 00:33
To my knowledge, none of the active Capistrano maintainers use Symfony. This makes it really tricky to verify correctness of pull requests and reproduce issues.

What would be tremendously helpful in this case is:
* A pull request with support for Symfony 4
* Documentation about how this impacts prior versions of Symfony (and reasoning as to why prior versions should be unsupported if desired, aka upstream support schedules)
* Best case, a test suite which proves that this all works, probably something like the [Vagrant acceptance tests in upstream Capistrano](https://github.com/capistrano/capistrano/tree/master/features)

**Comment by Prometee** [comment] 2018-01-04 23:45
There is some work to do to add symfony_directory_structure > 3.4 but I don't know what to do with sensio_distribution_version (I don't use this for now)

Work on Symfony 3.4 project and should work with 4.X because 3.4 has the same directory structure :
```
set :symfony_directory_structure, 3
set :sensio_distribution_version, 5

set :app_path, nil
set :web_path, "public"

set :app_config_path, nil
set :log_path,  fetch(:var_path) + "/log"

set :controllers_to_clear, []

set :assets_install_path, fetch(:web_path)

set :linked_dirs, [fetch(:log_path)]
```

**Comment by Prometee** [comment] 2018-01-08 10:23
But you have to manage :

- .env for command line by hand with export MY_VAR="..." in your ~/.profile or use the [capistrano-dotenv gem ](https://github.com/jplethier/capistrano-dotenv) to make those exports available during the execution of capistrano scripts.
- and build or write an .htaccess for apache, or configure your nginx vhosts following the doc : https://symfony.com/doc/current/setup/web_server_configuration.html

**Comment by Soullivaneuh** [comment] 2018-01-10 01:33
See also #85

**Comment by Nyholm** [comment] 2018-03-05 19:56
I will brush up my ruby skills and try to look into to this. I've just gotten the responsibility of the merge button. Any PRs are welcome.

**Comment by xavismeh** [comment] 2018-03-26 16:45
Required changes I had to do using the **RC3** (`deploy.rb`):
```ruby
set :linked_files, ['.env']
set :composer_install_flags, '--no-interaction --quiet --optimize-autoloader'
```

1. First line overrides the list of files shared across releases. I did reset instead of override (`fetch(:linked_files`) because we do not have the `app/config/parameters.yml` file anymore, which is default value in this release.

2. Second line should will remove the default `--no-dev` flag from the composer install command, which will allow to have `symfony/dotenv` package installed and avoid missing environment variables definitions error. That's obviously not an optimal solution, but to make it cleaner, I'd recommend to move `symfony/dotenv` lib in the `require` block instead of the `require-dev`, which is the default definition.

Otherwise, no problem encountered with default settings \o/

**Comment by Nyholm** [comment] 2018-03-26 16:47
Okey. Thank you. 

Yeah, one should rather move `symfony/dotenv` to `require`.

**Comment by xavismeh** [comment] 2018-03-26 16:49
I will personally go for this yes :)

**Comment by xavismeh** [comment] 2018-07-24 07:31
Maybe this issue could be closed, couldn't it ?

**Comment by Nyholm** [comment] 2018-07-24 07:40
I'll keep it open until a PR is merged. It is good for a reference.

**Comment by xavismeh** [comment] 2018-07-27 09:31
Is that something we want to do? Removing the `--no-dev` flag during composer install or moving `symfony/dotenv` to `require` block is a decision that would probably need to be taken at a project level but not in the tool, WDYT ?

**Comment by dachinat** [comment] 2018-09-06 07:48
I was getting serious error with Monolog (Memory allocation exhausted) and spent a lot of time investigating. This occurs if `var/log` is a linked directory. Don't know how you managed to have it linked.

**Comment by xavismeh** [comment] 2018-09-06 19:19
@dachinat if it can help, the only settings regarding the logs folder I have were/are the following:
```ruby
set :log_path, "var/log"
set :file_permissions_paths, [fetch(:log_path), fetch(:cache_path)]
```

**Comment by Nyholm** [comment] 2018-09-06 20:41
Lets fix this now!

**Closed** 2018-09-10 17:32 UTC
